src/Entity/PasswordUpdate.php
<?php

namespace App\Entity;


use Symfony\Component\Validator\Constraints as Assert;


class PasswordUpdate
{


    private $oldPassword;
    /**
     * @Assert\Length(min = 8 , minMessage ="Votre mot de passe doit faire au moins 8 caractéres")
     */
    private $newPassword;
    /**
     * @Assert\Length(min = 8 , minMessage ="Votre mot de passe doit faire au moins 8 caractéres")
     */
    
    private $ConfirmPassword;
    /**
     * @Assert\EqualTo( propertyPath="newPassword" , message ="Confirmé votre nouveau mot de passe")
     * 
     */
    public function getOldPassword(): ?string
    {
        return $this->oldPassword;
    }

    public function setOldPassword(string $oldPassword): self
    {
        $this->oldPassword = $oldPassword;

        return $this;
    }

    public function getNewPassword(): ?string
    {
        return $this->newPassword;
    }

    public function setNewPassword(string $newPassword): self
    {
        $this->newPassword = $newPassword;

        return $this;
    }

    public function getConfirmPassword(): ?string
    {
        return $this->ConfirmPassword;
    }

    public function setConfirmPassword(string $ConfirmPassword): self
    {
        $this->ConfirmPassword = $ConfirmPassword;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Url::class, mappedBy="user")
     */
    private $urls;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    public function __construct()
    {
        $this->urls = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Url[]
     */
    public function getUrls(): Collection
    {
        return $this->urls;
    }

    public function addUrl(Url $url): self
    {
        if (!$this->urls->contains($url)) {
            $this->urls[] = $url;
            $url->setUser($this);
        }

        return $this;
    }

    public function removeUrl(Url $url): self
    {
        if ($this->urls->removeElement($url)) {
            // set the owning side to null (unless already changed)
            if ($url->getUser() === $this) {
                $url->setUser(null);
            }
        }

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getDate(): string
    {
        return $this->Date;
    }

    public function setDate(string $Date): self
    {
        $this->Date = $Date;
        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdr(): ?string
    {
        return $this->adr;
    }

    public function setAdr(?string $adr): self
    {
        $this->adr = $adr;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Entity\Password;
use App\Entity\PasswordUpdate;
use App\Security\EmailVerifier;
use App\Form\PasswordUpdateType;
use App\Form\RegistrationFormType;
use Symfony\Component\Mime\Address;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class CompteController extends AbstractController
{
    #[Route('/compte/profil', name: 'app_profil')]
    public function index(): Response
    {
        return $this->render('compte/profil.html.twig', [
            'controller_name' => 'CompteController',
        ]);
    }
    private $emailVerifier;

    public function __construct(EmailVerifier $emailVerifier)
    {
        $this->emailVerifier = $emailVerifier;
    }

    #[Route('/compte/edit', name: 'app_edit')]
    public function edit(Request $request)
    {
        $user = $this->getUser();

        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $manger = $this->getDoctrine()->getManager();
            $manger->persist($user);
            $manger->flush();

            $this->emailVerifier->sendEmailConfirmation(
                'app_verify_email',
                $user,
                (new TemplatedEmail())
                    ->from(new Address('sassimotaze99@gmail.com', 'ATC Bot'))
                    ->to($user->getEmail())
                    ->subject('Bienvenue chez nous !')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );
            return $this->redirectToRoute('app_profil');
        }
        return $this->render('compte/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/compte/edit_motdepass', name: 'app_mdpup')]
    public function updatePassword(Request $request, UserPasswordHasherInterface $passwordEncoder)
    {
        $passwordUpdate = new PasswordUpdate();
        $user = $this->getUser();
        $form = $this->createForm(PasswordUpdateType::class, $passwordUpdate);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if (!password_verify($passwordUpdate->getOldPassword(), $user->getPassword())) {
                $form->get('oldPassword')->addError(new FormError("Le mot de passe que vous avez tapé n'est pas votre mot de passe actuel ! "));
            } else {
                $newPassword = $passwordUpdate->getNewPassword();
                $password = $passwordEncoder->hashPassword($user, $newPassword);
                $user->setPassword($password);
                $manager = $this->getDoctrine()->getManager();
                $manager->persist($user);
                $manager->flush();
            }
            return $this->redirectToRoute('app_logout');
        }
        return $this->render('compte/mdp.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/compte/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit
{% endblock %}

{% block body %}
	<div class="container  mt-5">
		<div class="row">
			<div class="col">
				{% for flashError in app.flashes('verify_email_error') %}
					<div class="alert alert-danger" role="alert">{{ flashError }}</div>
				{% endfor %}

				<h1 class="h3 mb-3 fw-bolder text-black" style="color:#263238;">Modifier Profil</h1>

				{{ form_start(form) }}
				{{ form_row(form.Nom, {
            label: 'Nom'
        }) }}
				{{ form_row(form.Prenom, {
            label: 'Prénom'
        }) }}
				{{ form_row(form.email, {
            label: 'Adresse e-mail'
        }) }}
				<div class="input-group date" data-provide="datepicker">

					<div class="input-group-addon">

						{{ form_row(form.Date, {
            label: 'Date de naissance'
        }) }}

					</div>
				</div>

				{{ form_row(form.adr, {
            label: 'Adresse '
        }) }}
				{{ form_row(form.type, {
            label: 'Profession'
        }) }}

				{{ form_row(form.tel, {
            label: 'Téléphone'
        }) }}
				{{ form_row(form.img, {
            label: 'Photo'
        }) }}


				<button type="submit" class="btn btn-primary mt-2 me-2">Modfication</button>
				{{ form_end(form) }}
			</div>
			<div class="col col-lg-6">
				<img src="/images/formulaire-dinscription.png" alt="" srcset="">
			</div>
		</div>
	</div>
</div>{% endblock %}

templates/compte/mdp.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit
{% endblock %}

{% block body %}
	<div class="container  mt-5">
		<h1 class="h3 mb-3 fw-bolder text-black" style="color:#263238;" >Confidentialité</h1>
		{{ form_start(form) }}
		
		{{ form_row(form.oldPassword, {
            label: 'Ancien Mot De Passe'
        }) }}

		{{ form_row(form.newPassword, {
            label: 'Nouveau Mot de passe'
        }) }}

		{{ form_row(form.confirmPassword, {
            label: 'Confirmation Mot De Passe'
        }) }}
		<button type="submit" class="btn btn-primary mt-2">Modification</button>
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/compte/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil
{% endblock %}


{% block body %}
	<div class="container mt-5">
    <div class="main-body">
          <!-- /Breadcrumb -->  
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{app.user.img}}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{app.user.prenom}} {{app.user.nom}} </h4>
                      <p class="text-secondary mb-1">{{app.user.type}}</p>
                      <p class="text-muted font-size-sm">{{app.user.adr}}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Prénom </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{app.user.prenom}} 
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Nom</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{app.user.nom}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Téléphone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{app.user.tel}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{app.user.email}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Date de naissance </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{app.user.date}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Liens Raccourcis</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{app.user.urls.count}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-info " target="__blank" href="{{ path('app_edit') }}">Modfication</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
    </div>
{% endblock %}

{% block javascripts %}{% endblock %}