src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Url::class, mappedBy="user")
     */
    private $urls;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    public function __construct()
    {
        $this->urls = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Url[]
     */
    public function getUrls(): Collection
    {
        return $this->urls;
    }

    public function addUrl(Url $url): self
    {
        if (!$this->urls->contains($url)) {
            $this->urls[] = $url;
            $url->setUser($this);
        }

        return $this;
    }

    public function removeUrl(Url $url): self
    {
        if ($this->urls->removeElement($url)) {
            // set the owning side to null (unless already changed)
            if ($url->getUser() === $this) {
                $url->setUser(null);
            }
        }

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getDate(): string
    {
        return $this->Date;
    }

    public function setDate(string $Date): self
    {
        $this->Date = $Date;
        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdr(): ?string
    {
        return $this->adr;
    }

    public function setAdr(?string $adr): self
    {
        $this->adr = $adr;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>CUTURL-
			{% block title %}{% endblock %}
		</title>
		<link
		rel="icon" href="/images/cat2.png" type="image/x-icon">
		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
		<link rel="stylesheet" href="style.css">
		<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
		<script type="text/javascript">
			let globalData;
		</script>
		<!-- JQuery -->

		<!-- Bootstrap tooltips -->
		<!-- Bootstrap core JavaScript --><script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"> </script>
		<script type="text/javascript" src="/js/jquery-3.6.0.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css" rel="stylesheet"/>

	</head>
	<body>
		<header>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
				<div class="container-fluid">
					<a class="navbar-brand" href="{{path('app_homepage') }}"><img src="/images/logo17.png" alt="" width="80" height="30"></a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							{% if is_granted('IS_AUTHENTICATED_FULLY') %}
								<li class="nav-item">
									
									<a class="nav-link " href="{{path('app_homepage') }}"><i class="bi bi-house-door"></i> Accueil</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_solutions')}}">Les Solutions</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_traits')}}">Les Traits</a>
								</li>
								<li class="nav-item">
									{% if app.user.urls.count %}
										<a class="nav-link" href="{{ path('url_list') }}">Mes Liens</a>
									{% endif %}
								</li>
							{% else %}
								<li class="nav-item">
									<a class="nav-link " href="{{path('app_homepage') }}"><i class="bi bi-house-door"></i>  Accueil</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_tarification')}}">Les Tarifications</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_solutions')}}">Les Solutions</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_traits')}}">Les Traits</a>
								</li>
							{% endif %}
						</ul>
					</div>
				</div>
		
				<div class="collapse navbar-collapse pe-5 me-2" id="navbarNavDarkDropdown">
				<ul class="navbar-nav ">
					<li class="nav-item dropdown">
						{% if is_granted('IS_AUTHENTICATED_FULLY') %}
							<a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								<img src="{{app.user.img}}" class="rounded-circle" height="35" alt=" Man" loading="lazy"/>
								{{app.user.prenom}}
								{{app.user.nom}}
							</a>
						{% else %}
							<a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								<img src="/images/avatar1.jpg" class="rounded-circle" height="35" alt="Black and White Portrait of a Man" loading="lazy"/>
							</a>
						{% endif %}
						<ul class="dropdown-menu dropdown-menu-dark pe-5 me-5 " aria-labelledby="navbarDarkDropdownMenuLink">
							{% if is_granted('IS_AUTHENTICATED_FULLY') %}
								<li>
									<a class="dropdown-item " href="{{ path('app_profil') }}"> <i class="bi bi-person-lines-fill"></i> Mon Compte</a>

								</li>
								<li>
									<a class="dropdown-item " href="{{ path('app_edit') }}"><i class="bi bi-gear"></i> Modifier mon profil</a>
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_mdpup') }}"><i class="bi bi-lock-fill"></i> Confidentialité</a>
								</li>
								<hr>
								<li >
									<a class="dropdown-item" href="{{ path('app_logout') }}"> <i class="bi bi-box-arrow-right"></i> Déconnexion</a>
								</li>
							{% else %}
								<li >
									<a class="dropdown-item " href="{{ path('app_login') }}"><i class="bi bi-box-arrow-in-right"></i> Connexion</a>
								</li>
								<hr>
								<li>
									<a class="dropdown-item " href="{{ path('app_tarification') }}"><i class="bi bi-person-plus"></i> Inscription</a>
								</li>
							{% endif %}
						</ul>
					</li>
				</ul>
				</div>
			</nav>
		</header>
	</body>

</html>{% block body %}{% endblock %}
{% block footer %}{% endblock %}
<!-- FOOTER -->
<footer class="text-centertext-whitemt-5 mt-5 " style="background-color: #f1f1f1;"><!-- Copyright -->
<div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">© 2020 Copyright:<a class="text-dark">Advanced Consulting</a>
</div><!-- Copyright --></footer>

templates/base1.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>CUTURL-
			{% block title %}{% endblock %}
		</title>
		<link
		rel="icon" href="/images/cat2.png" type="image/x-icon">
		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
		<script type="text/javascript">
			let globalData;
		</script>
		<!-- JQuery -->

		<!-- Bootstrap tooltips -->
		<!-- Bootstrap core JavaScript --><script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"> </script>
		<script type="text/javascript" src="/js/jquery-3.6.0.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css" rel="stylesheet"/>

	</head>
	<body>
		<header>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
				<div class="container-fluid">
					<a class="navbar-brand" href="{{path('app_homepage') }}"><img src="/images/logo17.png" alt="" width="80" height="30"></a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							{% if is_granted('IS_AUTHENTICATED_FULLY') %}
								<li class="nav-item">
									<a class="nav-link " href="{{path('app_homepage') }}">Accueil</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_solutions')}}">Solutions</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_traits')}}">Les Traits</a>
								</li>
								<li class="nav-item">
									{% if app.user.urls.count > 0 %}
										<a class="nav-link" href="{{ path('url_list') }}">Mes Liens</a>
									{% endif %}
								</li>
							{% else %}
								<li class="nav-item">
									<a class="nav-link " href="{{path('app_homepage') }}">Accueil</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_tarification')}}">Tarification</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_solutions')}}">Solutions</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{path('app_traits')}}">Les Traits</a>
								</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</div>

			<div class="collapse navbar-collapse me-5" id="navbarNavDarkDropdown">
				<ul class="navbar-nav ">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							<img src="/images/avatar1.jpg" class="rounded-circle" height="35" alt="Black and White Portrait of a Man" loading="lazy"/>
						</a>
						<ul class="dropdown-menu dropdown-menu-dark me-5 " aria-labelledby="navbarDarkDropdownMenuLink">
							{% if is_granted('IS_AUTHENTICATED_FULLY') %}
								<li>
									<a class="dropdown-item" href="{{ path('app_profil') }}">{{app.user.prenom}} {{app.user.nom}}</a>

								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_edit') }}">Paramètres</a>
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_logout') }}">Déconnexion</a>
								</li>
							{% else %}
								<li>
									<a class="dropdown-item" href="{{ path('app_tarification') }}">Inscription</a>
									
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_login') }}">Connexion</a>
								</li>
							{% endif %}
						</ul>
					</li>
				</ul>
			</div>
		</body>
	</body>
</html></nav>
</body></html></header>{% block body %}{% endblock %} 
<!-- FOOTER -->
		<footer class="text-center text-white mt-5" style="background-color: #f1f1f1;">
  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" >Advanced Consulting</a>
  </div>
  <!-- Copyright -->
</footer>
{% block footer %}
{% endblock %}</body></html>